version: '3'
services:
  unstructured:
    container_name: unstructured
    image: downloads.unstructured.io/unstructured-io/unstructured:latest
    networks:
      - reach
    command: tail -f /dev/null
  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"
    networks:
      - reach
  searxng:
    image: searxng/searxng
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    networks:
      - reach
  reach:
    image: reach
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./reach_core:/usr/src/app/reach_core
    build: ./
    environment:
      SEARX_URL: ${SEARX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - reach

networks:
  reach:
    driver: bridge
