version: '3'
services:
  searxng:
    image: searxng/searxng
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    networks:
      - reach
  reach:
    image: reach
    volumes:
      - ./frontend:/usr/src/app/frontend
      - ./reach_core:/usr/src/app/gpt_researcher
    build: ./
    environment:
      SEARX_URL: ${SEARX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - reach

networks:
  reach:
    driver: bridge
