version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    networks:
      - reach
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    networks:
      - reach
  reach:
    build: .
    image: reach13/reach:latest
    volumes:
      - ./reach-app-grid:/usr/src/app/react_app
    environment:
      SEARX_URL: ${SEARX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - reach
  reach-frontend:
    build:
      context: ./reach-app-grid
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    networks:
      - reach
    environment:
      - REACT_APP_BACKEND_URL=http://reach:8000

networks:
  reach:
    driver: bridge
