services:
  # ollama:
  #     image: ollama/ollama:latest
  #     volumes:
  #       - ./Modelfile:/Modelfile
  #       - ./Hermes-2-Pro-Llama-3-8B-F16.gguf:/models/Hermes-2-Pro-Llama-3-8B-F16.gguf
  #     ports: 
  #       - "11434:11434"
  #     networks:
  #       - reach
  ollama:
    image: ollama/ollama:latest
    ports: 
      - "11434:11434"
    networks:
      - reach-network
  searxng:
    image: searxng/searxng:latest
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    networks:
      - reach-network
  reach-next-app:
    build: ./reach-next-app
    image: reach-next-app:latest
    volumes:
      - ./reach-next-app:/usr/src/app/reach-next-app
    ports:
      - "3000:3000"
    networks:
      - reach-network
  reach:
    build: ./backend
    image: reach13/reach:latest
    volumes:
      - ./backend:/usr/src/app/backend
    environment:
      SEARX_URL: ${SEARX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - reach-network

networks:
  reach-network:
    driver: bridge
