version: '3'
services:
  ollama:
    image: ollama/ollama
    ports: 
      - "11434:11434"
    networks:
      - reach
  searxng:
    image: searxng/searxng
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    ports:
      - "8080:8080"
    networks:
      - reach
  reach:
    image: reach
    volumes:
      - ./reach-react-app:/usr/src/app/react_app
      # - ./frontend:/usr/src/app/frontend
      - ./reach_core:/usr/src/app/reach_core
    build: ./
    environment:
      SEARX_URL: ${SEARX_HOST}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    networks:
      - reach

networks:
  reach:
    driver: bridge
