name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update submodules
        run: |
          git submodule update --remote --merge

      - name: Commit changes
        run: |
          git config --global user.email "will@extendyourreach.ai"
          git config --global user.name "Will"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update all submodules"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main