name: Test macOS Installation Script on Linux

on: [pull_request]

jobs:
  test-mac-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose --version

      - name: Run Installation Script
        run: |
          chmod +x ./mac-reach-install.sh
          ./mac-reach-install.sh