name: Test macOS Installation Script

on: [pull_request]

jobs:
  test-mac-install:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          brew install docker-compose
          docker-compose --version

      - name: Run Installation Script
        run: |
          chmod +x ./mac-reach-install.sh
          ./mac-reach-install.sh