name: Test macOS Installation Script

on: [pull_request]

jobs:
  test-mac-install:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Docker
        run: |
          brew install docker docker-compose
          docker --version
          docker-compose --version

      - name: Start Docker Daemon
        run: open /Applications/Docker.app

      - name: Wait for Docker
        run: |
          while ! docker system info > /dev/null 2>&1; do
            echo "Waiting for Docker to start..."
            sleep 1
          done

      - name: Test Installation Script
        run: |
          chmod +x ./mac-reach-install.sh
          ./mac-reach-install.sh